version: 2

jobs:
  test:
    docker:
      - image: cimg/go:1.17

    steps:
      - checkout
      # golangci-lintによるLinterを実行
      - run:
          name: Install GolangCI-Lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.43.0
      - run:
          name: Run GolangCI-Lint
          command: ./bin/golangci-lint run --disable-all --enable=govet,errcheck,staticcheck,gosimple
      # 単体テストを実行
      - run:
          name: Run all unit tests
          command: go test -v ./...

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
